$(document).ready(function(){ 
    $("barra").focus(function(){
        $("#divt").html("");
        $("#divt").hide();
    });
    $("opc").focus(function(){
        $("#divt").html("");
        $("#divt").hide();
    });
})
